apiVersion: v1 #application pod
kind: Pod
metadata:
  name: app-pod
  labels:
    name: app-pod
    app: vue-project
spec:
  containers:
  - name: app
    image: gcr.io/academic-notch-342921/vue-project
    ports:
      - containerPort: 8080

---
apiVersion: v1 #internal service
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service
    app: vue-project
spec:
  selector:
    name: app-pod
    app: vue-project
  ports:
    - name: http
      port: 5000
      targetPort: 8080

---
apiVersion: apps/v1 #app inter ingress
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: http://34.69.96.174:80
    http:
      paths:
      - path: /
        backend:
          serviceName: app-service
          servicePort: http
