apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    name: app-pod
    app: vue-project
spec:
  containers:
  - name: app
    image: gcr.io/vueproject-338818/vue-project-3
    ports:
      - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service
    app: vue-project
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 8080
  selector:
    name: app-pod
    app: vue-project