apiVersion: v1 #application pod
kind: Pod
metadata:
  name: app-pod
  labels:
    name: app-pod
    app: vue-project
spec:
  containers:
  - name: app
    image: gcr.io/divine-camera-344312/vue-project
    ports:
      - containerPort: 8080

---
apiVersion: v1 #internal service
kind: Service
metadata:
  name: app-service
  labels:
    name: app-service
    app: vue-project
spec:
  type: ClusterIP
  selector:
    name: app-pod
    app: vue-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1 #app inter ingress
kind: Ingress
metadata:
  name: app-ingress

spec:
  rules:
    - host: crismaragno.com
      http:
        paths:
          - path: /bar
            pathType: Exact
            backend:
              service:
                name:  app-service
                port:
                  number: 80