apiVersion: v1
kind: Service
metadata:
  name: app-service-test
  labels:
    name: app-service-test
    app: vue-project
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 3200
  selector:
    name: app-service
    app: vue-project