kind: Deployment #ingress controller
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress
  namespace: default
  labels:
    k8s-app: vue-project
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: vue-project
  template:
    metadata:
      labels:
        k8s-app: vue-project
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
        - name: admin
          containerPort: 8080
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO

---
kind: Service #Create NodePorts for External Access
apiVersion: v1
metadata:
  name: traefik-ingress-service
  namespace: default
spec:
  selector:
    k8s-app: vue-project
  ports:
    - protocol: TCP
      port: 80
      name: web
    - protocol: TCP
      port: 8080
      name: admin
  type: NodePort