kind: Deployment #ingress controller
apiVersion: apps/v1
metadata:
  name: traefik
  labels:
    app: vue-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vue-project
  template:
    metadata:
      labels:
        app: vue-project
    spec:
      serviceAccountName: traefik-ingress
      containers:
        - name: traefik
          image: traefik:v2.6
          args:
            - --entrypoints.web.address=:80
            - --providers.kubernetesingress
          ports:
            - name: web
              containerPort: 80

---
kind: Service #Create NodePorts for External Access
apiVersion: v1
metadata:
  name: traefik
spec:
  type: LoadBalancer
  selector:
    app: vue-project
  ports:
    - protocol: TCP
      port: 80
      name: web
      targetPort: 80